name: ci-python-workflow
on:
  pull_request:
    branches:
      - develop
      
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.9'
      - run: pip install -U pip
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install --no-interaction --no-ansi
      - run: poetry run pytest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: marlonleiteal/fc2-ci-python:latest
