name: ci-python-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.9'
      - run: pip install -U pip
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest
        env:
          POETRY_VIRTUALENVS_CREATE: false